// Pure presentation-layer reformat of the existing Recommendation Engine
// output (bizHealth.insights / bizHealth.topPriorities, generated by
// server/services/recommendations.js::generateInsights — already sorted
// by priorityScore). No new fetches, no new LLM call, no invented text —
// this only restructures fields that already exist into a tighter,
// consulting-style summary.

function firstSentence(str) {
  if (!str) return '';
  const idx = str.search(/\.\s/);
  return idx === -1 ? str : str.slice(0, idx + 1);
}

export default function ExecutiveBrief({ insights, topPriorities }) {
  if (!insights || insights.length === 0) return null;

  const bullets = insights.slice(0, 5);
  const actions = (topPriorities && topPriorities.length > 0 ? topPriorities : insights.slice(0, 3));

  return (
    <div className="mb-6 rounded-xl border border-[var(--color-line)] bg-[var(--color-surface)] p-6">
      <div className="flex items-center gap-2 mb-4">
        <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-[var(--color-primary-tint)] text-[var(--color-primary)]">
          <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
            <polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2" />
          </svg>
        </div>
        <h2 className="text-base font-semibold text-[var(--color-ink)]">Executive Brief</h2>
      </div>

      <div className="grid gap-6 md:grid-cols-2">
        <div>
          <p className="text-[11px] font-semibold uppercase tracking-wider text-[var(--color-ink-faint)] mb-2">Executive Summary</p>
          <ul className="space-y-2">
            {bullets.map((ins, i) => (
              <li key={i} className="text-sm text-[var(--color-ink-soft)] leading-relaxed flex gap-2">
                <span className="shrink-0 text-[var(--color-primary)]">•</span>
                <span>
                  <span className="text-[var(--color-ink)] font-medium">{firstSentence(ins.observation)}</span>
                  {ins.businessImpact && <span> {firstSentence(ins.businessImpact)}</span>}
                </span>
              </li>
            ))}
          </ul>
        </div>

        <div>
          <p className="text-[11px] font-semibold uppercase tracking-wider text-[var(--color-ink-faint)] mb-2">Recommended Actions</p>
          <ol className="space-y-2.5">
            {actions.slice(0, 3).map((ins, i) => (
              <li key={i} className="flex gap-2.5 text-sm">
                <span className="shrink-0 flex h-5 w-5 items-center justify-center rounded-full bg-[var(--color-primary-tint)] text-[10px] font-bold text-[var(--color-primary)]">
                  {i + 1}
                </span>
                <span className="text-[var(--color-ink)] leading-relaxed">{firstSentence(ins.recommendedAction)}</span>
              </li>
            ))}
          </ol>
        </div>
      </div>
    </div>
  );
}
