/**
 * Tests for the dashboard's PDF export.
 *
 * The report replaced a client-side html2canvas + jsPDF screenshot of the
 * live DOM, which had two failure modes worth guarding against here: it
 * produced output that was blurry or outright broken depending on what the
 * browser happened to be rendering, and it could not render currency text
 * correctly — pdfkit's built-in Helvetica has no glyph for ₦ and silently
 * substitutes a broken-bar character, confirmed by generating a real PDF and
 * re-extracting its text with pdfjs-dist. Both are guarded below: the first
 * by asserting the output is a real, non-trivial PDF; the second by
 * generating one with insight text that carries a genuine ₦ and checking the
 * extracted text for the character that must not appear.
 *
 * These tests read the actual generated bytes with pdfjs-dist rather than
 * only checking "did buildDashboardPdf resolve" — a promise resolving proves
 * pdfkit didn't throw, not that the page is legible.
 */

const { buildDashboardPdf } = require('../services/reports/dashboardPdfReport');

let passed = 0, failed = 0;
const failures = [];
const section = (n) => console.log(`\n=== ${n} ===`);
function test(name, fn) {
  return Promise.resolve().then(fn).then(() => { passed++; console.log(`  ok    ${name}`); })
    .catch((e) => { failed++; failures.push({ name, message: e.message }); console.log(`  FAIL  ${name}\n        ${e.message}`); });
}
const assert = (c, m) => { if (!c) throw new Error(m || 'Assertion failed'); };
const eq = (a, e, m) => { if (a !== e) throw new Error(`${m || 'mismatch'}: expected ${JSON.stringify(e)}, got ${JSON.stringify(a)}`); };

// pdfjs-dist ships ESM-only in this version; the rest of the suite is
// CommonJS, so the reader is loaded once via dynamic import and reused.
let pdfjs;
async function extractText(buffer) {
  if (!pdfjs) pdfjs = await import('pdfjs-dist/legacy/build/pdf.mjs');
  const doc = await pdfjs.getDocument({ data: new Uint8Array(buffer) }).promise;
  let text = '';
  for (let i = 1; i <= doc.numPages; i++) {
    const page = await doc.getPage(i);
    const content = await page.getTextContent();
    text += content.items.map((it) => it.str).join(' ') + '\n';
  }
  return { text, pageCount: doc.numPages };
}

const MINIMAL_CTX = {
  organizationName: 'Test Pharmacy',
  kpis: [{ label: 'Total Revenue', value: 'N100,000', accent: '#1F6F5C' }],
};

async function main() {
  section('Produces a real PDF, not a broken or empty one');

  await test('output starts with the PDF magic header', async () => {
    const buf = await buildDashboardPdf(MINIMAL_CTX);
    eq(buf.slice(0, 5).toString(), '%PDF-');
  });

  await test('a minimal report is still a legible one-page PDF', async () => {
    const buf = await buildDashboardPdf(MINIMAL_CTX);
    const { text, pageCount } = await extractText(buf);
    eq(pageCount, 1);
    assert(text.includes('Test Pharmacy'), 'organization name rendered');
    assert(text.includes('Total Revenue'), 'KPI label rendered');
    assert(text.includes('N100,000'), 'KPI value rendered');
  });

  await test('an empty context still produces a valid PDF, not a crash', async () => {
    const buf = await buildDashboardPdf({});
    eq(buf.slice(0, 5).toString(), '%PDF-');
  });

  section('Currency in prose text never reaches the reader as a broken glyph');

  await test('a real ₦ inside an insight is rewritten before drawing', async () => {
    const buf = await buildDashboardPdf({
      ...MINIMAL_CTX,
      insights: [{ observation: 'Revenue grew from ₦349,900 to ₦14,158,050.', recommendedAction: 'Investigate the ₦ jump.', impact: 2 }],
    });
    const { text } = await extractText(buf);
    assert(!text.includes('¦'), `broken-bar glyph leaked into the PDF: ${text}`);
    assert(!text.includes('₦'), 'pdfkit cannot render this glyph at all, so it must not appear either');
    assert(text.includes('N349,900') && text.includes('N14,158,050'), 'the number itself is preserved, only the symbol changes');
  });

  await test('a real ₦ inside an inventory executive note is rewritten too', async () => {
    const buf = await buildDashboardPdf({
      ...MINIMAL_CTX,
      inventory: { kpis: [], notes: [{ insight: 'N₦4,800,000 sits in overstock.', action: 'Discount it.', severity: 'high' }] },
    });
    const { text } = await extractText(buf);
    assert(!text.includes('¦'), `broken-bar glyph leaked into the PDF: ${text}`);
  });

  await test('KPI values built with fmtN never carried the raw glyph in the first place', async () => {
    // Documents the contract the route relies on: every value in `kpis` is
    // expected to already be a formatted string (via fmtN/fmtNum), so this
    // is a smoke test that passing one through changes nothing.
    const buf = await buildDashboardPdf({ organizationName: 'X', kpis: [{ label: 'Revenue', value: 'N5,000' }] });
    const { text } = await extractText(buf);
    assert(text.includes('N5,000'));
  });

  section('Sections are skipped cleanly when their data is absent');

  await test('no monthlyRevenue means no Revenue Trend section, not an empty chart', async () => {
    const buf = await buildDashboardPdf(MINIMAL_CTX);
    const { text } = await extractText(buf);
    assert(!text.includes('Revenue Trend'), 'section header should not appear with nothing to plot');
  });

  await test('a single month of revenue is too little to chart and is skipped', async () => {
    const buf = await buildDashboardPdf({ ...MINIMAL_CTX, monthlyRevenue: [{ month: '2026-07', revenue: 100 }] });
    const { text } = await extractText(buf);
    assert(!text.includes('Revenue Trend'), 'one point cannot show a trend');
  });

  await test('two or more months does chart', async () => {
    const buf = await buildDashboardPdf({
      ...MINIMAL_CTX,
      monthlyRevenue: [{ month: '2026-06', revenue: 100 }, { month: '2026-07', revenue: 200 }],
    });
    const { text } = await extractText(buf);
    assert(text.includes('Revenue Trend'), 'two points is enough to show a trend');
  });

  await test('no inventory data means no Inventory Risk section', async () => {
    const buf = await buildDashboardPdf(MINIMAL_CTX);
    const { text } = await extractText(buf);
    assert(!text.includes('Inventory Risk'));
  });

  await test('inventory notes alone (no KPI cards) still render the section', async () => {
    // A sales-only current upload can still carry inventory widgets with an
    // executive note but no cost data to build a KPI card from — the section
    // must not be dropped just because half its content is missing.
    const buf = await buildDashboardPdf({
      ...MINIMAL_CTX,
      inventory: { kpis: [], notes: [{ insight: 'Slow movers found.', action: 'Discount them.', severity: 'medium' }] },
    });
    const { text } = await extractText(buf);
    assert(text.includes('Inventory Risk'));
    assert(text.includes('Slow movers found.'));
  });

  await test('no business health means no Business Health section', async () => {
    const buf = await buildDashboardPdf(MINIMAL_CTX);
    const { text } = await extractText(buf);
    assert(!text.includes('Business Health'));
  });

  await test('only the top 3 insights are drawn as priorities, however many are passed', async () => {
    const insights = Array.from({ length: 6 }, (_, i) => ({
      observation: `Observation number ${i + 1}`, recommendedAction: 'Do something.', impact: 1,
    }));
    const buf = await buildDashboardPdf({ ...MINIMAL_CTX, insights });
    const { text } = await extractText(buf);
    assert(text.includes('Observation number 1') && text.includes('Observation number 3'));
    assert(!text.includes('Observation number 4'), 'a 4th priority should not be drawn');
  });

  section('Multi-page pagination');

  await test('enough content to overflow a page produces a real page 2', async () => {
    const topProducts = Array.from({ length: 8 }, (_, i) => ({ name: `Product ${i}`, revenue: 1000 - i }));
    const insights = Array.from({ length: 3 }, (_, i) => ({
      observation: `A fairly long observation about product performance number ${i} that takes up real space on the page.`,
      recommendedAction: 'A correspondingly detailed recommended action with enough words to occupy several lines of the report.',
      impact: 2,
    }));
    const buf = await buildDashboardPdf({
      ...MINIMAL_CTX,
      bizHealth: { overallScore: 70, rating: 'Stable', pillars: [{ name: 'Sales Performance', score: 80, band: 'good' }] },
      insights,
      monthlyRevenue: Array.from({ length: 9 }, (_, i) => ({ month: `2026-0${i + 1}`, revenue: 1000 * (i + 1) })),
      topProducts,
    });
    const { pageCount, text } = await extractText(buf);
    assert(pageCount >= 2, `expected the content to overflow to a second page, got ${pageCount}`);
    assert(text.includes(`page 1 of ${pageCount}`), 'footer reports the real page count');
  });

  console.log(`\n${passed} passed, ${failed} failed`);
  if (failed > 0) {
    console.log('\nFailures:');
    failures.forEach((f) => console.log(`  - ${f.name}: ${f.message}`));
    process.exit(1);
  }
}

main();
